Use assertIn and assertNotIn
Tests should use:

    self.assertIn(value, list)
    self.assertNotIn(value, list)

instead of:

    self.assertTrue(value in list)
    self.assertFalse(value in list)

because assertIn and assertNotIn raise more meaningful errors:

    self.assertIn(3, [1, 2])
    >>> MismatchError: 3 not in [1, 2]

    self.assertTrue(3 in [1, 2])
    >>> AssertionError: False is not true

Change-Id: I64322073c3808a03e5a3d485a7eea257ab1403e6
Related-Bug: #1218713